You are connected to the database: ('pyinfra_db1',)
Database connection is succeeded at  2022-03-10 13:02:02
Database connection closed
You are connected to the database: ('pyinfra_db1',)
Database connection is succeeded at  2022-03-10 13:02:20
Database connection closed
